network.host: 0.0.0.0
cluster.routing.allocation.disk.watermark.low: 150mb
cluster.routing.allocation.disk.watermark.high: 100mb
cluster.routing.allocation.disk.watermark.flood_stage: 50mb
rest.action.multi.allow_explicit_index: true
